participants/iit2024169.txt
Issue: #1 
Added iit2024169.txt in the participants folder
=> Added iit2024169 as a participant

participants/IIT2024098.txt
Issue : #1 
Introduction to Github
=> Edit IIT2024098.txt

participants/iit2024099, participants/iit2024099.txt
issue: https://github.com/opencodeiiita/Techtonic/issues/1
added a txt file in github and push it
and deleted extra file that i made
=> adding a txt file

participants/iit2024101.txt
issue: #1 
added a new text file in github
=> added file

participants/iit2024099.txt
Reverts opencodeiiita/Techtonic#13
=> Revert "adding a txt file"

participants/IEC2024081.txt
Issue: #1 
Add info about myself
=> Add info about myself

participants/iit2024236.txt
Issue: #1
Added iit2024236.txt as required by the task
=> Added iit2024236.txt

IEC2024081.md
Issue: #7 
Image of our beautiful campus
=> Image of our beautiful campus

participants/IIT2024243.txt
=> Added IIT2024243.txt 

iit2024243.md
=> Added iit2024243.md

participants/iec2023048.txt
=> iec2023048.txt added

README.md, participants/IIT2024235.txt
=> added IIT2024235.txt

IIT2024098.md
Issue:  #7 
Added image from pavilion
=> Image from Pavilion

participants/IEC2024019.txt
Issue : #1 
Added info txt file as required
=> Added participant txt file

iit2024262.md
=> issue:#7 Added Photo of BasketBall Court

participants/iit2024245.txt
=> #Issue 01 response

iit2024169.md
Issue: #7 
Added beautiful image of our campus during GAM
IIT2024169
=> Added beautiful image of our campus during GAM

IEC2024076.md
Issue: #7 
added image of AAA building in a .md file
=> added IEC2024076.md

IEC2024076.html
Issue: #46 
added IEC024076.html with my details
=> added IEC2024076.html

IEC2024081.html
Issue: #46 
added IEC2024081.html
=> added IEC2024081.html

participants/IIT2024013.txt
Issue: #1 
Added IIT2024013.txt file
=> Added IIT2024013.txt file

IIT2024236.html
Issue: #46 
Added html file with required format
=> Added html file

IIT2024098.html
ISSUE: #46 
Created IIT2024098.html file as required
=> Created HTML File

iit2024245.md
=> Issue #07 response iit2024245

iit2024245.html
=> My beautiful campus

participants/iit2024092.txt
=> file creation

IIT2024092.html
=> Added IIT2024092.html

iit2024243.html
Issue: #46 
Previously my img src was my local path to the image, but now i had uploaded the image on google drive and made it open for all and then used the link to share.
=> Added iit2024243.html

participants/IEC2024047.txt
Issue : #1 
Added a .txt file with my details
=> added IEC2024047.txt

IIT2024206.md
Issue: #7 
added IIT2024206.md in branch-College
=> added IIT2024206.md

IIT2024099.md
=> added photo in clg branch

IIT2024240.md
=> Added image of Admin block

IIT2024249.html
=> Adding HTML file

participants/IIB2024001.txt
Issue: #1 
Created the file with my enrollment number as the name, it contains brief intro about me
=> Created IIB2024001.txt

IIB2024001.md
Issue: #7 
Added image of AAA building of our beautiful campus
=> Added image of our campus

iit2024246.html
Issue: #46 
Creating a webpage
=> Created the webpage

IIT2024162.html
=> IIT2024162.html

IIB2024001.html
Issue: #46 
Created a webpage.
=> Created IIB2024001.html

IIT2024206.html
=> added IIT2024206.html

IIT2024098.txt
issue: #93 
Made web to-do list and hosted it
=> Made To-Do List

IEC2024081.txt
Issue: #93 
To-Do Prompting !!
=> Complete To-Do Prompting task

participants/IIT2024250.txt
=> added IIT2024250.txt

IIT2024098.txt
issue: #151 
Made CV Webpage using html, css, js and added link to repo and webpage
=> Made CV Webpage
